version: 2.1

orbs:
  python: circleci/python@1.2.0

workflows:
  version: 2
  build-and-test:
    jobs:
      - python/test:
          version: "3.8"
          steps:
            - checkout
            - run: pip install -r requirements.txt
            - run: pytest
